config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  devise_for :users

  root to: 'home#index'
  resources :posts, only: %i[new create show] do
    resources :comments, only: %i[create]
    resource :likes, only: %i[create]
    resource :like, only: %i[destroy]
  end

  resources :categories, only: %i[new create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :category
  belongs_to :creator, class_name: 'User'

  has_many :likes, dependent: :destroy, class_name: 'PostLike'
  has_many :comments, dependent: :destroy, class_name: 'PostComment'

  validates :title, presence: true, length: { minimum: 1 }
  validates :body, presence: true, length: { minimum: 50 }
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  has_ancestry

  validates :content, presence: true, length: { minimum: 5 }
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :post
  belongs_to :user, foreign_key: 'creator_id', inverse_of: :likes

  validates :creator_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy, foreign_key: :creator_id, inverse_of: :creator
  has_many :likes, dependent: :destroy, inverse_of: :user, class_name: 'PostLike'
  has_many :comments, dependent: :destroy, inverse_of: :user, class_name: 'PostComment'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  private

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path, alert: t('base.please_login')
    end
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def new
    @category = Category.new
  end

  def create
    @category = Category.build(permitted_params)

    if @category.save
      redirect_to root_path, notice: I18n.t('.success')
    else
      render :new, status: :unprocessable_content, alert: I18n.t('.failure')
    end
  end

  private

  def permitted_params
    params.expect(category: %i[name])
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = post.comments.build(user: current_user, **permitted_params)

    if @comment.save
      redirect_to @post, notice: t('.published')
    else
      flash[:alert] = @comment.errors.full_messages.join(', ')
      redirect_to @post
    end
  end

  private

  def post
    @post ||= Post.find(params[:post_id])
  end

  def permitted_params
    params.expect(post_comment: %i[content parent_id])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = post.likes.build(user: current_user)

    if @like.save
      redirect_to @post, notice: t('.liked')
    else
      redirect_to @post, alert: t('.unliked')
    end
  end

  def destroy
    @like = post.likes.find_by(user: current_user)

    if @like&.destroy
      redirect_to @post, notice: t('.like_removed')
    else
      redirect_to @post, alert: t('.like_remoing_errors')
    end
  end

  private

  def post
    @post ||= Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def show
    @post = Post.find(params[:id])
    @like = current_user ? @post.likes.find_by(creator_id: current_user.id) : false
    @comments = @post.comments.roots
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(permitted_params)

    if @post.save
      redirect_to root_path, notice: I18n.t('posts.create.success')
    else
      render :new, status: :unprocessable_content, alert: I18n.t('posts.create.failure')
    end
  end

  private

  def permitted_params
    params.expect(post: %i[title body category_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def format_comment_date(date)
    I18n.l(date, format: :short)
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/categories/new.html.slim
h1 Новая категория

= simple_form_for @category do |f|
  = f.input :name
  = f.button :submit, class: 'btn-primary'

app/views/comments/_comment.html.slim
.card.mt-2.rounded-0 id="comment-#{comment.id}"
  .card-header.border-0
    a.me-2 href="#comment-#{comment.id}" #
    span.me-2 = comment.user.email
    span.fs-6.text-muted = format_comment_date(comment.created_at)
  .card-body.border-0
    p.card-text = comment.content

  - if current_user
    .card-footer.border-0
      a.fs-6.text-decoration-underline.text-lowercase[
        type="button"
        aria-expanded="false"
        aria-controls="response_comment-#{comment.id}"
        data-bs-target="#response_comment-#{comment.id}"
        data-bs-toggle="collapse"
        href="#"
      ]
        = t('.reply')

    .ms-2.collapse id="response_comment-#{comment.id}"
      = render 'comments/form', comment: comment

  - comment.children.each do |child_comment|
    .ms-4
      = render 'comments/comment', comment: child_comment

app/views/comments/_form.html.slim
= simple_form_for(PostComment.new, url: post_comments_path(comment&.post || post)) do |f|
  = f.input :content, label: false,
            input_html: { class: 'form-control', rows: 3 },
            wrapper_html: { class: 'mb-2' }
  = f.hidden_field :parent_id, value: comment&.id
  = f.submit t('.submit_comment'), class: 'btn btn-primary btn-sm'

app/views/home/index.html.slim
h1 Коллективный блог

.row
  - @posts.each do |post|
    .col-md-12
      .card.mb-3
        .card-body
          h2.h5.card-title
            = link_to post.title, post_path(post), class: 'link-dark text-decoration-none'
          .card-text.mb-2
            = post.body

          .text-right.small.text-muted.mt-auto
            span.me-2
              = t('.liked', count: post.likes.count)
            span.me-2
              = time_ago_in_words(post.created_at)
            span
              = post.creator.email

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      - if content_for?(:title)
        = yield(:title)
      - else
        | Rails Project 64

    meta[name="viewport" content="width=device-width,initial-scale=1"]
    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="application-name" content="Rails Project 64"
    meta name="mobile-web-app-capable" content="yes"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'

    = yield :head

    / Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!)
    / = tag.link rel: "manifest", href: pwa_manifest_path(format: :json)

    link rel="icon" href="/icon.png" type="image/png"
    link rel="icon" href="/icon.svg" type="image/svg+xml"
    link rel="apple-touch-icon" href="/icon.png"

  body.d-flex.flex-column.h-100
    header
      .container.mb-2
        .d-flex.flex-wrap.align-items-center.py-2.border-bottom
          .navbar.navbar-expand-md.navbar-light.me-auto
            a.navbar-brand.me-md-4
              logo
          ul.nav.nav-pills
            - if user_signed_in?
              li.nav-item.me-2
                = link_to t('.add_post'), new_post_path, class: 'nav-link link-dark'
              li.nav-item.me-2
                = link_to t('.sign_out'), destroy_user_session_path, class: 'nav-link link-dark', data: { turbo_method: :delete }
            - else
              li.nav-item.me-2
                = link_to t('.sign_in'), new_user_session_path, class: 'nav-link link-dark'
              li.nav-item.me-2
                = link_to t('.register'), new_user_registration_path, class: 'nav-link link-dark'

    main.container.my-4
      - if notice
        .alert.alert-info
          = notice
      - if alert
        .alert.alert-warning
          = alert
      = yield

app/views/posts/new.html.slim
h1 Новая статья

= simple_form_for @post do |f|
  = f.input :title
  = f.input :body, as: :text
  = f.association :category
  = f.button :submit, class: 'btn-primary'

app/views/posts/show.html.slim
ol.breadcrumb
  li.breadcrumb-item
    = link_to t('.all_posts'), root_path
  li.breadcrumb-item.active
    = @post.category.name

.row.justify-content-center.mt-4
  article.col-12
    h1.mb-4.mb-lg-5
      = @post.title
    .post-content
      = simple_format(@post.body)
    .d-flex.justify-content-between.mt-5
      #post-section
        span.me-2
          = @post.creator.email
        span
          = time_ago_in_words(@post.created_at)
      #likes-section
        span.me-2
          = @post.likes.count

        - if current_user
          - if @like.present?
            = link_to post_like_path(@post), class: 'link-dark', data: { turbo_stream: true, turbo_method: :delete }
              i.bi.bi-hand-thumbs-up-fill
          - else
            = link_to post_likes_path(@post), class: 'link-dark', data: { turbo_method: :post }
              i.bi.bi-hand-thumbs-up
        - else
          i.bi.bi-hand-thumbs-up

.lead.mt-3#comment-section
  span
    = t('.comments')

  = render 'comments/form', post: @post, comment: nil
  - @comments.each do |comment|
    = render 'comments/comment', comment: comment